# -*- coding: utf-8 -*-
"""Text to image converstion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhWDKDWCc3jKejKpjPiGskr1LduEXIXK
"""

# Installing required libraries
!pip install diffusers transformers accelerate scipy ftfy Pillow

# Checking if a GPU is available or not, if not it will setup accordingly
import torch
if torch.cuda.is_available():
    device = "cuda"
    print("Using GPU")
else:
    device = "cpu"
    print("Using CPU")

# Importing required modules
from diffusers import StableDiffusionPipeline
from PIL import Image
import io
import matplotlib.pyplot as plt

# Loading pre-trained stable diffusion model
model_id = "runwayml/stable-diffusion-v1-5"  # Or "stabilityai/stable-diffusion-2-1"
pipe = StableDiffusionPipeline.from_pretrained(model_id).to(device)

# Generating an image and displaying a image
def generate_and_display_image(prompt):
    """
    Generates an image from a text prompt using Stable Diffusion and displays it.
    Args:
        prompt: The text prompt to generate the image from.
    """
    try:
        image = pipe(prompt).images[0]
        # Display the image using matplotlib
        plt.imshow(image)
        plt.axis('off')  # Hide axes
        plt.show()
        return image
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

# Example for generating a image
prompt = "Planets"
generated_image = generate_and_display_image(prompt)

# printing type of image
if generated_image:
    print(type(generated_image))

